#!/bin/bash
#
# Check if the Broker Status of the Progress OpenEdge JMS Adaper
# is ACTIVE (exit code 0) or not (exit code 1)
#
# Copyright 2024 TVH Parts Holding NV, IT department, CoE Progress, Vichtseweg 129, 8790 Waregem, Belgium.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ADAPTERDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

[[ $(${ADAPTERDIR}/adaptman s | grep "Broker Status" | cut -d ':' -f 2 | xargs) == "ACTIVE" ]] && exit 0 || exit 1
